services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
